version: '3'
services:

  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home:/home
      - ../minidream-challenge-2018:/home/shared
      - /home/${USER}/
    ports:
      - "8787:8787"

