version: '3'
services:
  reverse_proxy:
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 443:443
  rstudio:
    container_name: rstudio
    build:
      context: ./rstudio
      dockerfile: Dockerfile
    volumes:
      - /home:/home
      - ../minidream-challenge-2018:/home/shared
      - /home/${USER}/
    ports:
      - "8787:8787"
